<<<<<<< HEAD
blank_issues_enabled: true
contact_links:
  - name: ğŸ“– Community Firmware documentation
    url: https://cr6community.github.io/
    about: CR-6 documentation
  - name: ğŸ‰ Community Firmware release notes
    url: https://github.com/CR6Community/Marlin/releases
    about: Release notes of previous releases, also contains instructions on various features
  - name: ğŸ‘¤ CR-6 SE / CR-6 MAX Users Facebook group
    url: https://www.facebook.com/groups/cr6community
    about: Please ask and answer questions here.
  - name: ğŸ‘¤ CR-6 subreddit /r/cr6
    url: https://www.reddit.com/r/CR6/
    about: Please ask and answer questions here.
  - name: ğŸ•¹ CR6 Community Firmware on on Discord
    url: https://discord.gg/PfMufwZTCX
    about: Join the Discord server for support and discussion.
  - name: ğŸ“º CR6 Community Firmware Videos on YouTube
    url: https://www.youtube.com/results?search_query=cr6+community+firmware
    about: Tutorials and more from Marlin users all around the world. Great for new users!
  - name: ğŸ’¸ Want to donate to the Community Firmware?
    url: https://github.com/CR6Community/Marlin/#credits
    about: Would like to buy a beer/coffee for the developers? We appreciate it!
  - name: ğŸ’¸ Want to donate to the upstream project - Marlin?
    url: https://www.thinkyhead.com/donate-to-marlin
    about: Please take a look at the various options to support Marlin Firmware's development financially!
=======
blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Marlin Documentation
    url: http://marlinfw.org/
    about: Lots of documentation on installing and using Marlin.
  - name: ğŸ‘¤ MarlinFirmware Facebook group
    url: https://www.facebook.com/groups/1049718498464482
    about: Please ask and answer questions here.
  - name: ğŸ•¹ Marlin on Discord
    url: https://discord.gg/n5NJ59y
    about: Join the Discord server for support and discussion.
  - name: ğŸ”— Marlin Discussion Forum
    url: http://forums.reprap.org/list.php?415
    about: A searchable web forum hosted by RepRap dot org.
  - name: ğŸ“º Marlin Videos on YouTube
    url: https://www.youtube.com/results?search_query=marlin+firmware
    about: Tutorials and more from Marlin users all around the world. Great for new users!
  - name: ğŸ’¸ Want to donate?
    url: https://www.thinkyhead.com/donate-to-marlin
    about: Please take a look at the various options to support Marlin Firmware's development financially!
>>>>>>> upstream/2.0.x
