#
# clean-closed.yml
# Remove obsolete labels when an Issue or PR is closed
#

name: Clean Closed

on:
  pull_request:
    types: [closed]
  issues:
    types: [closed]

jobs:
  remove_label:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        label:
          - "S: Don't Merge"
          - "S: Hold for 2.1"
          - "S: Please Merge"
          - "S: Please Test"
          - "help wanted"
          - "Needs: Discussion"
          - "Needs: Documentation"
          - "Needs: More Data"
          - "Needs: Patch"
          - "Needs: Testing"
          - "Needs: Work"

    steps:
      - uses: actions/checkout@v3
      - name: Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: ${{ matrix.label }}
